version: '3.9'
services:
  db:
    ports:
      - "${DATABASE_PORT:-6432}:5432"

  dev:
    image: kartoza/sanbi:test
    environment:
      - DISABLE_2FA=${DISABLE_2FA=True}
    volumes:
      - ../django_project:/home/web/django_project
    ports:
      # for django test server
      - "61100:8080"
    command:
      - tail
      - -f
      - /dev/null

  worker:
    volumes:
      - ../django_project:/home/web/django_project
    image: kartoza/sanbi:test